[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
marketplace = "A2LjHJg4r7WZNYUESKFZsq1Survafi8r16n63PqUfuqE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/tushar/Q3_2025_Builder_TusharPamnani/marketplace/Turbin3-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
